Repository smapiot/piral, pull requests merged in 2019-09, with the labels that each got.

#74 Feature/#47 cli plugins
  CHANGELOG.md
  docs/commands/debug-pilet.md
  docs/commands/debug-piral.md
  src/packages/piral-cli/README.md
  src/packages/piral-cli/src/api.ts
  src/packages/piral-cli/src/cli.ts
  src/packages/piral-cli/src/commands.ts
  src/packages/piral-cli/src/index.ts
  src/packages/piral-cli/src/pb-cli.ts
  src/packages/piral-cli/src/pilet-cli.ts
  src/packages/piral-cli/src/piral-cli.ts
  src/packages/piral-cli/src/plugin.ts
  src/packages/piral-cli/src/questionnaire.ts
  src/packages/piral-cli/src/resolvers.ts
  src/packages/piral-cli/src/select.ts
  src/packages/piral-cli/src/types.ts
  tools/generate-command-docs.js
Labels: cli, plugin

#75 Updated template for piral instance scaffolding: parsing pilet query
  src/packages/piral-cli/templates/piral-backend.js.ejs
Labels: bug

#76 Updated the tutorial for Publishing Pilets to Feed Service
  docs/diagrams/api-key-management.png
  docs/diagrams/api-keys.png
  docs/diagrams/creating-feed.png
  docs/diagrams/feed-overview.png
  docs/diagrams/feed-service.png
  docs/diagrams/ms-login.svg
  docs/diagrams/new-api-key.png
  docs/diagrams/published-pilets.png
  docs/tutorials/02-getting-started.md
  docs/tutorials/03-publishing-pilets.md
Labels: documentation, enhancement
