Repository smapiot/piral, pull requests merged in 2020-09, with the labels that each got.

#317 Enhanced Documentation
  src/pages/docs/src/codegen/gen-bundlers.js
  src/pages/docs/src/codegen/paths.js
  src/pages/docs/src/codegen/sitemap.codegen
Labels: documentation

#319 Add ability to set and retrieve state during login flow
  .github/CONTRIBUTING.md
  CHANGELOG.md
  src/plugins/piral-oidc/README.md
  src/plugins/piral-oidc/src/setup.test.ts
  src/plugins/piral-oidc/src/setup.ts
  src/plugins/piral-oidc/src/types.ts
Labels: auth, plugin

#324 Plugin Overview Page Feature + Visual alignment bundler doc pages
  src/pages/docs/src/codegen/gen-bundlers.js
  src/pages/docs/src/codegen/gen-overview-page.js
  src/pages/docs/src/codegen/search.codegen
  src/pages/docs/src/codegen/sitemap.codegen
  src/pages/docs/src/scripts/components/ImageCard.tsx
  src/pages/docs/src/scripts/components/index.ts
Labels: documentation, enhancement

#325 0.12.2
  CHANGELOG.md
  docs/commands/publish-pilet.md
  docs/commands/validate-pilet.md
  docs/diagrams/blazor-architecture.png
  docs/reference/metadata.md
  docs/specs/feed-api-specification.md
  docs/tutorials/01-introduction.md
  docs/tutorials/08-the-piral-cli.md
  src/converters/piral-blazor/README.md
  src/framework/piral-core/package.json
  src/framework/piral-core/src/helpers.tsx
  src/pages/docs/src/codegen/gen-bundlers.js
  src/pages/docs/src/codegen/gen-overview-page.js
  src/pages/docs/src/codegen/search.codegen
  src/pages/docs/src/codegen/sitemap.codegen
  src/pages/docs/src/scripts/components/ImageCard.tsx
  src/pages/docs/src/scripts/components/index.ts
  src/tooling/piral-cli-webpack/extend-config.js
  src/tooling/piral-cli-webpack/package.json
  src/tooling/piral-cli/src/apps/publish-pilet.ts
  src/tooling/piral-cli/src/apps/validate-pilet.ts
  src/tooling/piral-cli/src/apps/validate-piral.ts
  src/tooling/piral-cli/src/commands.ts
  src/tooling/piral-cli/src/common/config.ts
  src/tooling/piral-cli/src/common/http.ts
  src/tooling/piral-cli/src/rules/pilet-stays-small.ts
  src/utilities/piral-debug-utils/README.md
  src/utilities/piral-debug-utils/package.json
  src/utilities/piral-debug-utils/src/debug.ts
  src/utilities/piral-debug-utils/src/emulator.ts
  src/utilities/piral-debug-utils/src/index.ts
  src/utilities/piral-debug-utils/tsconfig.json
  tools/generate-command-docs.js
Labels: release
