Repository smapiot/piral, pull requests merged in 2020-05, with the labels that each got.

#213 Fixed the buttons on the landing page's banner being misaligned on mobile devices.
  CHANGELOG.md
  lerna.json
  src/initializers/create-pilet/package.json
  src/initializers/create-piral-instance/package.json
  src/packages/piral-adal/package.json
  src/packages/piral-aurelia/package.json
  src/packages/piral-auth/package.json
  src/packages/piral-axios/package.json
  src/packages/piral-base/package.json
  src/packages/piral-blazor/package.json
  src/packages/piral-cli/package.json
  src/packages/piral-cli/src/parcel/bundler.ts
  src/packages/piral-containers/package.json
  src/packages/piral-core/package.json
  src/packages/piral-dashboard/package.json
  src/packages/piral-elm/package.json
  src/packages/piral-ember/package.json
  src/packages/piral-ext/package.json
  src/packages/piral-feeds/package.json
  src/packages/piral-fetch/package.json
  src/packages/piral-forms/package.json
  src/packages/piral-hyperapp/package.json
  src/packages/piral-inferno/package.json
  src/packages/piral-lazy/package.json
  src/packages/piral-litel/package.json
  src/packages/piral-menu/package.json
  src/packages/piral-mithril/package.json
  src/packages/piral-modals/package.json
  src/packages/piral-ng/package.json
  src/packages/piral-ngjs/package.json
  src/packages/piral-notifications/package.json
  src/packages/piral-oauth2/package.json
  src/packages/piral-oidc/package.json
  src/packages/piral-preact/package.json
  src/packages/piral-pwa/package.json
  src/packages/piral-react-15/package.json
  src/packages/piral-redux/package.json
  src/packages/piral-riot/package.json
  src/packages/piral-search/package.json
  src/packages/piral-ssr-utils/package.json
  src/packages/piral-svelte/package.json
  src/packages/piral-tracking/package.json
  src/packages/piral-translate/package.json
  src/packages/piral-urql/package.json
  src/packages/piral-vue/package.json
  src/packages/piral/package.json
  src/packages/siteless/package.json
  src/pages/docs/package.json
  src/pages/www/package.json
  src/pages/www/src/style/_custom.scss
  src/samples/sample-cross-fx/package.json
  src/samples/sample-piral-core/package.json
  src/samples/sample-piral/package.json
Labels: bug, documentation, page

#218 add BaseModalOIptions interface to piral-modals
  CHANGELOG.md
  src/packages/piral-modals/README.md
  src/packages/piral-modals/src/types.ts
Labels: enhancement

#221 Feature/#219 piral oidc redirects
  CHANGELOG.md
  src/packages/piral-oidc/README.md
  src/packages/piral-oidc/src/OidcError.ts
  src/packages/piral-oidc/src/setup.test.ts
  src/packages/piral-oidc/src/setup.ts
  src/packages/piral-oidc/src/types.ts
Labels: documentation, enhancement, plugin
