Repository smapiot/piral, pull requests merged in 2020-04, with the labels that each got.

#187 First implementation of the OAuth 2.0 and OIDC clients.
  src/packages/piral-oauth2/package.json
  src/packages/piral-oauth2/src/setup.ts
  src/packages/piral-oidc/package.json
  src/packages/piral-oidc/src/setup.ts
  src/pages/docs/src/assets/extensions/oauth.png
  src/pages/docs/src/assets/extensions/oidc.png
  yarn.lock
Labels: enhancement, plugin

#196 Release 0.11.2
  CHANGELOG.md
  docs/tutorials/18-authentication.md
  src/packages/piral-adal/README.md
  src/packages/piral-blazor/README.md
  src/packages/piral-blazor/infra.codegen
  src/packages/piral-blazor/package.json
  src/packages/piral-blazor/src/create.ts
  src/packages/piral-blazor/src/index.ts
  src/packages/piral-blazor/src/internal/Environment.ts
  src/packages/piral-blazor/src/internal/Platform/BootConfig.ts
  src/packages/piral-blazor/src/internal/Platform/Mono/MonoDebugger.ts
  src/packages/piral-blazor/src/internal/Platform/Mono/MonoPlatform.ts
  src/packages/piral-blazor/src/internal/Platform/Mono/MonoTypes.d.ts
  src/packages/piral-blazor/src/internal/Platform/Platform.ts
  src/packages/piral-blazor/src/internal/Platform/Url.ts
  src/packages/piral-blazor/src/internal/Platform/WebAssemblyConfigLoader.ts
  src/packages/piral-blazor/src/internal/Platform/WebAssemblyResourceLoader.ts
  src/packages/piral-blazor/src/internal/Rendering/BrowserRenderer.ts
  src/packages/piral-blazor/src/internal/Rendering/ElementReferenceCapture.ts
  src/packages/piral-blazor/src/internal/Rendering/EventDelegator.ts
  src/packages/piral-blazor/src/internal/Rendering/EventFieldInfo.ts
  src/packages/piral-blazor/src/internal/Rendering/EventForDotNet.ts
  src/packages/piral-blazor/src/internal/Rendering/LogicalElements.ts
  src/packages/piral-blazor/src/internal/Rendering/RenderBatch/OutOfProcessRenderBatch.ts
  src/packages/piral-blazor/src/internal/Rendering/RenderBatch/RenderBatch.ts
  src/packages/piral-blazor/src/internal/Rendering/RenderBatch/SharedMemoryRenderBatch.ts
  src/packages/piral-blazor/src/internal/Rendering/RenderBatch/Utf8Decoder.ts
  src/packages/piral-blazor/src/internal/Rendering/Renderer.ts
  src/packages/piral-blazor/src/internal/Rendering/RendererEventDispatcher.ts
  src/packages/piral-blazor/src/internal/Services/NavigationManager.ts
  src/packages/piral-blazor/src/internal/globals.ts
  src/packages/piral-blazor/src/internal/index.ts
  src/packages/piral-blazor/src/types.ts
  src/packages/piral-blazor/tsconfig.json
  src/packages/piral-cli/src/apps/build-piral.ts
  src/packages/piral-cli/src/apps/debug-pilet.ts
  src/packages/piral-cli/src/apps/declaration-piral.ts
  src/packages/piral-cli/src/common/archive.ts
  src/packages/piral-cli/src/common/debug.ts
  src/packages/piral-cli/src/common/declaration.ts
  src/packages/piral-cli/src/common/emulator.ts
  src/packages/piral-cli/src/common/index.ts
  src/packages/piral-cli/src/common/inspect.ts
  src/packages/piral-cli/src/common/log.ts
  src/packages/piral-cli/src/common/package.ts
  src/packages/piral-containers/src/types.ts
  src/packages/piral-core/src/components/ResponsiveLayout.tsx
  src/packages/piral-elm/src/create.ts
  src/packages/piral-feeds/src/types.ts
  src/packages/piral-forms/src/types.ts
  src/packages/piral-forms/src/withForm.tsx
  src/packages/piral-lazy/src/create.test.ts
  src/packages/piral-oauth2/README.md
  src/packages/piral-oidc/README.md
  src/packages/piral/src/utils/options.test.ts
  src/pages/docs/src/assets/extensions/blazor.png
  src/pages/docs/src/assets/extensions/oidc.png
  yarn.lock
Labels: release

#199 Cannot set property 'verbose' of undefined
  src/packages/piral-cli/src/common/log.ts
Labels: bug, cli, cross-platform

#202 Release 0.11.3
  CHANGELOG.md
  docs/questions/plugins.md
  docs/questions/tooling.md
  docs/tutorials/02-getting-started.md
  docs/tutorials/03-publishing-pilets.md
  docs/tutorials/07-development-workflow.md
  docs/tutorials/11-server-side-rendering.md
  docs/tutorials/README.md
  src/packages/piral-blazor/README.md
  src/packages/piral-cli/package.json
  src/packages/piral-cli/src/common/declaration.ts
  src/packages/piral-cli/src/common/log.ts
  src/packages/piral-cli/src/messages.ts
  src/packages/piral-core/src/components/ExtensionSlot.tsx
  src/packages/piral-core/src/modules/api.ts
  src/packages/piral-core/src/types/api.ts
  src/packages/piral-core/src/types/custom.ts
  src/packages/piral-core/src/types/extension.ts
  src/packages/piral-core/src/types/state.ts
  src/packages/piral-core/src/types/utils.ts
  src/packages/piral-modals/src/types.ts
  src/packages/piral/polyfills.js
  src/samples/sample-piral-core/src/pilets/dashboard.tsx
  src/samples/sample-piral-core/src/pilets/pilet1.tsx
  yarn.lock
Labels: release

#208 Correct URL
  src/pages/docs/src/pages/Home.tsx
Labels: bug, documentation, page
