Repository smapiot/piral, pull requests merged in 2020-08, with the labels that each got.

#301 Fixed "Available Plugins" link on homepage.
  src/pages/www/src/scripts/components/Features.tsx
Labels: bug, documentation

#303 Feature/add open dependency
  CHANGELOG.md
  src/tooling/piral-cli/package.json
  src/tooling/piral-cli/src/common/archive.test.ts
  src/tooling/piral-cli/src/common/browser.ts
  src/tooling/piral-cli/src/external/index.test.ts
  src/tooling/piral-cli/src/external/index.ts
  yarn.lock
Labels: bug, cli, enhancement

#298 Updated/Enhanced Framework Documentation
  src/converters/piral-blazor/README.md
  src/converters/piral-ember/README.md
  src/converters/piral-hyperapp/README.md
  src/converters/piral-mithril/README.md
  src/converters/piral-preact/README.md
  src/converters/piral-svelte/README.md
  src/framework/piral-base/src/types.ts
  src/framework/piral-core/src/types/api.ts
  src/framework/piral-core/src/types/state.ts
  src/framework/piral-core/src/types/utils.ts
Labels: documentation, enhancement
