Repository smapiot/piral, pull requests merged in 2022-03, with the labels that each got.

#484 Release 0.14.14
  CHANGELOG.md
  src/framework/piral-core/debug-pilet.ts
  src/framework/piral-core/src/components/DefaultRouteSwitch.tsx
  src/framework/piral-core/src/components/PiralRoutes.test.tsx
  src/framework/piral-core/src/components/PiralRoutes.tsx
  src/framework/piral-core/src/components/PiralView.tsx
  src/framework/piral-core/src/components/components.tsx
  src/framework/piral-core/src/components/index.ts
  src/framework/piral-core/src/state/createGlobalState.test.ts
  src/framework/piral-core/src/state/createGlobalState.ts
  src/framework/piral-core/src/types/components.ts
  src/framework/piral-core/src/types/state.ts
  src/samples/sample-piral/package.json
  src/templates/piral-template-empty/src/index.ts
  src/tooling/piral-cli-webpack5/src/webpack/bundler-run.ts
  src/tooling/piral-cli/src/common/scaffold.ts
  src/utilities/piral-debug-utils/src/DebugRouteSwitch.tsx
  src/utilities/piral-debug-utils/src/debug.ts
  src/utilities/piral-debug-utils/src/emulator.ts
  src/utilities/piral-debug-utils/src/types.ts
Labels: release

#485 Release 0.14.15
  CHANGELOG.md
  src/framework/piral-base/src/dependency.test.ts
  src/framework/piral-base/src/dependency.ts
  src/tooling/piral-cli/src/questionnaire.ts
  src/utilities/piral-debug-utils/src/debug.ts
Labels: release

#487 Upgrade to jest 26.x
  CHANGELOG.md
  jest.config.js
  package.json
  src/framework/piral-base/src/strategies.test.ts
  src/plugins/piral-axios/src/create.test.ts
  src/plugins/piral-fetch/src/create.test.ts
  src/plugins/piral-pwa/package.json
  src/utilities/piral-jest-utils/package.json
  yarn.lock
Labels: enhancement, tooling, repository

#488 Release 0.14.16
  .github/workflows/size.yml
  CHANGELOG.md
  docs/tutorials/23.2-monorepo-rush.md
  jest.config.js
  package.json
  src/converters/piral-blazor/src/converter.ts
  src/converters/piral-blazor/src/events.ts
  src/framework/piral-base/src/load.test.ts
  src/framework/piral-base/src/load.ts
  src/framework/piral-base/src/strategies.test.ts
  src/plugins/piral-axios/src/create.test.ts
  src/plugins/piral-fetch/src/create.test.ts
  src/plugins/piral-pwa/package.json
  src/utilities/piral-jest-utils/package.json
  tools/size-reporter.mjs
  yarn.lock
Labels: release

#491 Release 0.14.17
  CHANGELOG.md
  src/converters/piral-aurelia/src/converter.ts
  src/converters/piral-blazor/src/converter.ts
  src/converters/piral-blazor/src/interop.ts
  src/converters/piral-cycle/src/converter.ts
  src/converters/piral-elm/src/converter.ts
  src/converters/piral-ember/src/converter.ts
  src/converters/piral-hyperapp/src/converter.ts
  src/converters/piral-inferno/src/converter.ts
  src/converters/piral-litel/src/converter.ts
  src/converters/piral-mithril/src/converter.ts
  src/converters/piral-ng/src/converter.ts
  src/converters/piral-ngjs/src/converter.ts
  src/converters/piral-preact/src/converter.ts
  src/converters/piral-react-15/src/converter.ts
  src/converters/piral-riot/src/converter.ts
  src/converters/piral-solid/src/converter.ts
  src/converters/piral-svelte/src/converter.ts
  src/converters/piral-vue-3/src/converter.ts
  src/converters/piral-vue/src/converter.ts
  src/framework/piral-base/src/system.ts
  src/framework/piral-core/src/components/ForeignComponentContainer.tsx
  src/framework/piral-core/src/types/components.ts
Labels: release

#493 Release 0.14.18
  CHANGELOG.md
  src/framework/piral-base/src/dependency.ts
  src/tooling/piral-cli-webpack/src/plugins/SheetPlugin.ts
  src/tooling/piral-cli-webpack/src/webpack/common.ts
  src/tooling/piral-cli-webpack/src/webpack/pilet.ts
  src/tooling/piral-cli-webpack/src/webpack/piral.ts
  src/tooling/piral-cli-webpack5/src/plugins/SheetPlugin.ts
  src/tooling/piral-cli-webpack5/src/webpack/common.ts
  src/tooling/piral-cli-webpack5/src/webpack/pilet.ts
  src/tooling/piral-cli-webpack5/src/webpack/piral.ts
Labels: release

#495 improved test coverage in the piral-core package
  src/framework/piral-core/src/actions/portal.test.ts
  src/framework/piral-core/src/components/PiralView.test.tsx
  src/framework/piral-core/src/components/PiralView.tsx
  src/framework/piral-core/src/createInstance.test.tsx
  src/framework/piral-core/src/hooks/globalState-server.test.ts
  src/framework/piral-core/src/utils/extension.test.tsx
  src/framework/piral-core/src/utils/guid.test.ts
  src/framework/piral-core/src/utils/helpers.test.ts
  src/framework/piral-core/src/utils/media-server.test.ts
  src/framework/piral-core/src/utils/media.ts
  yarn.lock
Labels: core, repository

#496 Release 0.14.19
  CHANGELOG.md
  jest.config.js
  src/converters/piral-aurelia/convert.ts
  src/converters/piral-blazor/convert.ts
  src/converters/piral-cycle/convert.ts
  src/converters/piral-elm/convert.ts
  src/converters/piral-ember/convert.ts
  src/converters/piral-hyperapp/convert.ts
  src/converters/piral-inferno/convert.ts
  src/converters/piral-litel/convert.ts
  src/converters/piral-mithril/convert.ts
  src/converters/piral-ng/convert.ts
  src/converters/piral-ng/src/bootstrap.ts
  src/converters/piral-ng/src/converter.ts
  src/converters/piral-ng/src/module.ts
  src/converters/piral-ng/src/startup.ts
  src/converters/piral-ngjs/convert.ts
  src/converters/piral-preact/convert.ts
  src/converters/piral-react-15/convert.ts
  src/converters/piral-riot/convert.ts
  src/converters/piral-solid/convert.ts
  src/converters/piral-svelte/convert.ts
  src/converters/piral-vue-3/convert.ts
  src/converters/piral-vue/convert.ts
  src/framework/piral-core/src/utils/media.ts
  src/pages/docs/src/styles.scss
  src/tooling/piral-cli-webpack5/package.json
  src/tooling/piral-cli-webpack5/src/plugins/SheetLoader.ts
  src/tooling/piral-cli-webpack5/src/plugins/SheetPlugin.ts
  src/tooling/piral-cli/src/apps/build-pilet.ts
  src/tooling/piral-cli/src/apps/debug-pilet.ts
  src/tooling/piral-cli/src/apps/publish-pilet.ts
  src/tooling/piral-cli/src/commands.ts
  src/tooling/piral-cli/src/common/http.test.ts
  src/tooling/piral-cli/src/common/http.ts
  src/tooling/piral-cli/src/common/index.ts
  src/tooling/piral-cli/src/common/info.ts
  src/tooling/piral-cli/src/common/parallel.test.ts
  src/tooling/piral-cli/src/common/parallel.ts
  src/tooling/piral-cli/src/helpers.ts
  src/tooling/piral-cli/src/injectors/pilet.ts
  src/tooling/piral-cli/src/types/public.ts
  src/utilities/piral-jest-utils/src/config.ts
Labels: release

#497 Added more test to improve test coverage in the piral-core package
  src/framework/piral-core/src/RootListener.test.tsx
  src/framework/piral-core/src/actions/app.test.ts
  src/framework/piral-core/src/components/ExtensionSlot.test.tsx
  src/framework/piral-core/src/components/ExtensionSlot.tsx
  src/framework/piral-core/src/components/PiralView-server.test.tsx
  src/framework/piral-core/src/components/SwitchErrorInfo.test.tsx
  src/framework/piral-core/src/createInstance.test.tsx
  src/framework/piral-core/src/hooks/setter-server.test.ts
  src/framework/piral-core/src/hooks/setter.test.ts
  src/framework/piral-core/src/modules/element.test.ts
  src/framework/piral-core/src/state/withApi.test.tsx
  src/framework/piral-core/src/utils/extension.test.tsx
  src/framework/piral-core/src/utils/foreign.test.ts
  src/framework/piral-core/src/utils/state.test.ts
  yarn.lock
Labels: core, repository
